language: ruby
before_install:
- gem install bundler
script:
- bundle exec rake test
deploy:
  provider: heroku
  api_key:
    secure: SfD/maxqOYQKLMWyT+N/iQAK0xpOuUxvJaCfC3djbvFISRs/ApTZ8OpckQrq/QDSam8E9dBlVkoyr2aqwRde4LM12sKR1/LAu8pY46e8AbGJXUYe86F958bN9cObncyI2jy5K4Cm8Nls8mv1K/9sWXlS3Z/UEYUSt83raJIGBdE=
  app:
    master: yasslab-jp
notifications:
  webhooks:
  - https://idobata.io/hook/travis_ci/ef9a047f-66e6-4471-97db-3e278c70acf8
